### ISSUE TITLE
Cookbook http_stub_status_module not found

### ISSUE THREAD

**Issue by srinivasgumdelli** [chef-cookbooks/nginx#319]
I am trying to write a cookbook to install my rails application and I get the following error when I run `vagrant provision`

```
==> default: [2015-01-18T15:24:03+00:00] INFO: Forking chef instance to converge...
==> default: [2015-01-18T15:24:03+00:00] INFO: *** Chef 12.0.3 ***
==> default: [2015-01-18T15:24:03+00:00] INFO: Chef-client pid: 13888
==> default: [2015-01-18T15:24:09+00:00] INFO: Setting the run_list to ["recipe[apt]", "recipe[build-essential]", "recipe[rvm::vagrant]", "recipe[rvm::system]", "recipe[rvm::gem_package]", "recipe[nginx::source]"] from CLI options
==> default: [2015-01-18T15:24:09+00:00] INFO: Run List is [recipe[apt], recipe[build-essential], recipe[rvm::vagrant], recipe[rvm::system], recipe[rvm::gem_package], recipe[nginx::source]]
==> default: [2015-01-18T15:24:09+00:00] INFO: Run List expands to [apt, build-essential, rvm::vagrant, rvm::system, rvm::gem_package, nginx::source]
==> default: [2015-01-18T15:24:09+00:00] INFO: Starting Chef Run for nginx-berkshelf
==> default: [2015-01-18T15:24:09+00:00] INFO: Running start handlers
==> default: [2015-01-18T15:24:09+00:00] INFO: Start handlers complete.
==> default: /tmp/vagrant-chef/cd3bbd54c0efcf612e706f9728d04ed6/cookbooks/rvm/libraries/rvm_chef_user_environment.rb:49: warning: class variable access from toplevel
==> default: [2015-01-18T15:24:11+00:00] INFO: execute[Guard resource] ran successfully
==> default: [2015-01-18T15:24:11+00:00] WARN: Cloning resource attributes for group[rvm] from prior resource (CHEF-3694)
==> default: [2015-01-18T15:24:11+00:00] WARN: Previous group[rvm]: /tmp/vagrant-chef/cd3bbd54c0efcf612e706f9728d04ed6/cookbooks/rvm/recipes/vagrant.rb:34:in `from_file'
==> default: [2015-01-18T15:24:11+00:00] WARN: Current  group[rvm]: /tmp/vagrant-chef/cd3bbd54c0efcf612e706f9728d04ed6/cookbooks/rvm/recipes/system.rb:33:in `from_file'
==> default: [2015-01-18T15:24:11+00:00] INFO: gem_package resource has been patched to use provider Chef::Provider::Package::RVMRubygems and will install gems to the ruby-1.9.3-p429 RVM Ruby.
==> default: [2015-01-18T15:24:11+00:00] INFO: ohai plugins will be at: /etc/chef/ohai_plugins
==> default: [2015-01-18T15:24:12+00:00] INFO: ohai[custom_plugins] reloaded
==> default: [2015-01-18T15:24:12+00:00] WARN: MissingCookbookDependency:
==> default: Recipe `http_stub_status_module` is not in the run_list, and cookbook 'http_stub_status_module'
==> default: is not a dependency of any cookbook in the run_list.  To load this recipe,
==> default: first add a dependency on cookbook 'http_stub_status_module' in the cookbook you're
==> default: including it from in that cookbook's metadata.
==> default:
==> default: ================================================================================
==> default: Recipe Compile Error in /tmp/vagrant-chef/cd3bbd54c0efcf612e706f9728d04ed6/cookbooks/nginx/recipes/source.rb
==> default: ================================================================================
==> default:
==> default:
==> default: Chef::Exceptions::CookbookNotFound
==> default: ----------------------------------
==> default: Cookbook http_stub_status_module not found. If you're loading http_stub_status_module from another cookbook, make sure you configure the dependency in your metadata
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef/cd3bbd54c0efcf612e706f9728d04ed6/cookbooks/nginx/recipes/source.rb:91:in `block in from_file'
==> default:
==> default:   /tmp/vagrant-chef/cd3bbd54c0efcf612e706f9728d04ed6/cookbooks/nginx/recipes/source.rb:90:in `each'
==> default:
==> default:   /tmp/vagrant-chef/cd3bbd54c0efcf612e706f9728d04ed6/cookbooks/nginx/recipes/source.rb:90:in `from_file'
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef/cd3bbd54c0efcf612e706f9728d04ed6/cookbooks/nginx/recipes/source.rb:
==> default:
==> default:  84:    code <<-EOH
==> default:  85:      tar zxf #{::File.basename(src_filepath)} -C #{::File.dirname(src_filepath)}
==> default:  86:    EOH
==> default:  87:    not_if { ::File.directory?("#{Chef::Config['file_cache_path'] || '/tmp'}/nginx-#{node['nginx']['source']['version']}") }
==> default:  88:  end
==> default:  89:
==> default:  90:  node['nginx']['source']['modules'].each do |ngx_module|
==> default:  91>>   include_recipe ngx_module
==> default:  92:  end
==> default:  93:
==> default:  94:  configure_flags       = node.run_state['nginx_configure_flags']
==> default:  95:  nginx_force_recompile = node.run_state['nginx_force_recompile']
==> default:  96:
==> default:  97:  bash 'compile_nginx_source' do
==> default:  98:    cwd  ::File.dirname(src_filepath)
==> default:  99:    code <<-EOH
==> default: 100:      cd nginx-#{node['nginx']['source']['version']} &&
==> default:
==> default: [2015-01-18T15:24:12+00:00] ERROR: Running exception handlers
==> default: [2015-01-18T15:24:12+00:00] ERROR: Exception handlers complete
==> default: [2015-01-18T15:24:12+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-01-18T15:24:12+00:00] ERROR: Cookbook http_stub_status_module not found. If you're loading http_stub_status_module from another cookbook, make sure you configure the dependency in your metadata
==> default: [2015-01-18T15:24:12+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by sankalpsingha** [comment]
Could you solve this error? I am getting the same issue.

**Comment by jsw2** [comment]
nginx::http_stub_status_module

**Comment by iennae** [comment]
The issue looks like at the time that you were using this recipe that node['nginx']['source']['modules'] had http_stub_status_module included without fully qualifying it. If you take a look at this test within the cookbook:

https://github.com/chef-cookbooks/nginx/blob/22a1b6365755782e82067d61ab34a0569c5c1704/test/cookbooks/test/recipes/modules.rb
