### ISSUE TITLE
Ohai_plugin[nginx] (nginx::ohai_plugin line 29) had an error: NameError:

### ISSUE THREAD

**Issue by tden012** [chef-cookbooks/nginx#448]
### Cookbook version
7.0.2

### Chef-client version
12.6.0

### Platform Details
Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-25cf1c5d

### Scenario:
Trying to install nginx from source. 

### Steps to Reproduce:
1) Create metadata.rb with
```ruby
depends "build-essential", "2.2.3"
depends "apt", "2.7.0"
depends "nginx", "7.0.2"
```

2) Create attributes/default.rb file with:
```ruby
default['svr_rails']['nginx']['version'] = "1.7.0"
default['svr_rails']['nginx']['default_root'] = "/var/www/nginx"
default['svr_rails']['nginx']['dir'] = "/etc/nginx"
```

3) create recipes/default.rb with:
```ruby
node.default['apt']['compile_time_update'] = true
node.default['build-essential']['compile_time'] = true

include_recipe 'apt'
include_recipe 'build-essential'

node.default['nginx']['version'] = node['svr_rails']['nginx']['version']
node.default['nginx']['default_root'] = node['svr_rails']['nginx']['default_root']
node.default['nginx']['dir'] = node['svr_rails']['nginx']['dir']

include_recipe 'nginx::source'
```

4) Provision using Vagrant to AWS

### Expected Result:
Cookbooks compile and nginx is installed

### Actual Result:
Receive the following error

```
==> default: ================================================================================
==> default:   Recipe Compile Error in /var/chef/cache/cookbooks/svr_rails/recipes/default.rb
==> default:
==> default: ================================================================================
==> default:
==> default:
==> default:
==> default:
==> default: NameError
==> default:
==> default: ---------
==> default:
==> default: ohai_plugin[nginx] (nginx::ohai_plugin line 29) had an error: NameError: No resource, method, or local variable named `desired_plugin_path' for `Custom resource ohai_plugin from cookbook ohai action provider "nginx"'
==> default:
==> default:
==> default:
==> default: Cookbook Trace:
==> default:
==> default: ---------------
==> default:     /var/chef/cache/cookbooks/ohai/resources/plugin.rb:12:in `block in class_from_file'
==> default:
==> default:   /var/chef/cache/cookbooks/ohai/resources/plugin.rb:67:in `block in after_created'
==> default:
==> default:   /var/chef/cache/cookbooks/ohai/resources/plugin.rb:66:in `each'
==> default:     /var/chef/cache/cookbooks/ohai/resources/plugin.rb:66:in `after_created'
==> default:
==> default:
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:106:in `build'
==> default:
==> default:
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:308:in `build_resource'
==> default:
==> default:
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:265:in `declare_resource'
==> default:
==> default:   /var/chef/cache/cookbooks/nginx/recipes/ohai_plugin.rb:29:in `from_file'
==> default:
==> default:
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
==> default:
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
==> default:
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
==> default:
==> default:
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
==> default:
==> default:   /var/chef/cache/cookbooks/nginx/recipes/source.rb:36:in `from_file'
==> default:
==> default:
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
==> default:
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
==> default:
==> default:
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
==> default:
==> default:
==> default:   /var/chef/cache/cookbooks/svr_rails/recipes/default.rb:63:in `from_file'
==> default:
==> default:
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
==> default:
==> default:
==> default:
==> default:   Relevant File Content:
==> default:
==> default: ----------------------
==> default:   /var/chef/cache/cookbooks/ohai/resources/plugin.rb:
==> default:
==> default:
==> default:
==> default:
==> default:   5:  property :resource, [:cookbook_file, :template], default: :cookbook_file
==> default:     6:  property :variables, Hash
==> default:
==> default:   7:  property :compile_time, [true, false], default: true
==> default:
==> default:
==> default:   8:
==> default:
==> default:   9:  action :create do
==> default:
==> default:
==> default:  10:    # why create_if_missing you ask?
==> default:
==> default:  11:    # no one can agree on perms and this allows them to manage the perms elsewhere
==> default:    12>>   directory desired_plugin_path do
==> default:
==> default:  13:      action :create
==> default:
==> default:
==> default:  14:      recursive true
==> default:
==> default:  15:      not_if { ::File.exist?(desired_plugin_path) }
==> default:
==> default:  16:    end
==> default:
==> default:  17:
==> default:    18:    if new_resource.resource.eql?(:cookbook_file)
==> default:
==> default:
==> default:  19:      cookbook_file ::File.join(desired_plugin_path, new_resource.plugin_name + '.rb') do
==> default:
==> default:  20:        cookbook new_resource.cookbook
==> default:
==> default:  21:        source new_resource.source_file || "#{new_resource.plugin_name}.rb"
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:
==> default: Running handlers:
==> default: [2017-12-01T22:05:26+00:00] ERROR: Running exception handlers
==> default:
==> default: Running handlers complete
==> default:
==> default: [2017-12-01T22:05:26+00:00] ERROR: Exception handlers complete
==> default:
==> default: Chef Client failed. 0 resources updated in 03 seconds
==> default: [2017-12-01T22:05:26+00:00] INFO: Sending resource update report (run-id: bd5808b7-a939-4c02-be31-85074ad232a6)
==> default: [2017-12-01T22:05:27+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-12-01T22:05:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-12-01T22:05:27+00:00] ERROR: ohai_plugin[nginx] (nginx::ohai_plugin line 29) had an error: NameError: No resource, method, or local variable named `desired_plugin_path' for `Custom resource ohai_plugin from cookbook ohai action provider "nginx"'
==> default: [2017-12-01T22:05:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by tas50** [comment]
You'll want to upgrade to the latest release of Chef 12 or ideally 13/14 in order to remove the need for compat_resource. 12.6 is very very EOL at this point.
